<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <RootNamespace>DotCraft</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\DashBoard.html" />
    <EmbeddedResource Include="Resources\DashBoardLogin.html" />
    <EmbeddedResource Include="Resources\model-context-windows.json" />
    <EmbeddedResource Include="Skills\BuiltIn\**\*" />
    <EmbeddedResource Include="Plugins\BuiltIn\**\*" />
    <EmbeddedResource Include="Commands\Custom\BuiltIn\**\*" />
    <EmbeddedResource Include="Localization\Languages\*.json" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Alibaba.OpenSandbox" Version="0.1.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.3.0" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" Version="1.3.0-preview.260423.1" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.AGUI.AspNetCore" Version="1.3.0-preview.260423.1" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.OpenAI" Version="1.3.0-alpha.260423.1" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.3.0" />
    <PackageReference Include="ModelContextProtocol" Version="0.8.0-preview.1" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DotCraft.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
